try:
    do_something()
except Exception as e:
    print('exception')
